import { NextRequest, NextResponse } from 'next/server';
import path from 'path';
import { promises as fs } from 'fs';
import AdmZip from 'adm-zip';
import { supabaseServiceRole } from '@/lib/supabase';
import { getAuthenticatedUser } from '@/lib/auth-utils';
// Legacy patcher removed — patches are now generated by Agent 4 in the LangGraph pipeline
import { scanRateLimit } from '@/lib/rate-limit';

export async function POST(request: NextRequest) {
  try {
    // SECURITY FIX: CSRF Origin Check
    const origin = request.headers.get('origin');
    if (origin && origin !== process.env.NEXT_PUBLIC_APP_URL) {
      return NextResponse.json({ success: false, error: 'Forbidden. Invalid origin for CSRF.' }, { status: 403 });
    }

    // Authenticate user
    const user = await getAuthenticatedUser(request);
    if (!user) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    // SECURITY FIX: Rate Limiting
    if (scanRateLimit) {
      const { success, reset } = await scanRateLimit.limit(user.id);
      if (!success) {
        return NextResponse.json({ success: false, error: 'Rate limit exceeded' }, { 
          status: 429,
          headers: { 'Retry-After': Math.max(0, Math.ceil((reset - Date.now()) / 1000)).toString() }
        });
      }
    }

    const body = await request.json();
    const { projectId, export: shouldExport } = body;

    // Validate input
    if (!projectId) {
      return NextResponse.json({ success: false, error: 'Project ID is required' }, { status: 400 });
    }

    const supabase = supabaseServiceRole();

    // Verify project ownership
    const { data: project } = await supabase
      .from('projects')
      .select('id')
      .eq('id', projectId)
      .eq('user_id', user.id)
      .single();

    if (!project) {
      return NextResponse.json({ success: false, error: 'Project not found or access denied' }, { status: 404 });
    }

    // For export, we'll need to download from storage
    // For now, using /tmp which works on Vercel
    const projectPath = path.join('/tmp', `SecureForge-${projectId}`);
    
    // Note: In production, this should load from storage
    // For now, this is a placeholder - the actual patching should happen during orchestration
    // This route is mainly for exporting already-patched code

    if (shouldExport) {
      try {
        // Create ZIP file of the patched project
        const zip = new AdmZip();
        zip.addLocalFolder(projectPath);
        
        const zipBuffer = zip.toBuffer();
        
        // Log timeline event
        const { error: timelineError } = await supabase
          .from('timeline_events')
          .insert([
            {
              project_id: projectId,
              event_type: 'export',
              event_message: 'Patched code exported as ZIP file'
            }
          ]);
        
        if (timelineError) {
          console.error('Error logging timeline event:', timelineError);
          return NextResponse.json({ success: false, error: 'Failed to log export event' }, { status: 500 });
        }
        
        return new NextResponse(zipBuffer as any, {
          headers: {
            'Content-Type': 'application/zip',
            'Content-Disposition': 'attachment; filename="patched-code.zip"',
          },
        });
      } catch (zipError) {
        console.error('Error creating ZIP file:', zipError);
        return NextResponse.json({ success: false, error: 'Failed to create ZIP file' }, { status: 500 });
      }
    } else {
      // Get patches from database by joining with scans and vulnerabilities tables
      const { data: patches, error: patchesError } = await supabase
        .from('patches')
        .select(`
          *,
          vulnerabilities(file_path)
        `)
        .eq('vulnerabilities.scan.project_id', projectId);
      
      if (patchesError) {
        console.error('Error fetching patches:', patchesError);
        return NextResponse.json({ success: false, error: 'Failed to fetch patches' }, { status: 500 });
      }
      
      // Convert database patches to patch objects
      const patchObjects = patches.map(patch => ({
        file: patch.vulnerabilities?.file_path || '',
        change: 'Database patch',
        before: patch.before_code || undefined,
        after: patch.after_code || undefined
      }));
      
      // Patches are now generated and applied by Agent 4 in the LangGraph pipeline.
      // This legacy endpoint just returns the patch data from the database.
      return NextResponse.json({ 
        success: true, 
        patches: patchObjects,
        message: `Found ${patchObjects.length} patches. Patches are applied via the LangGraph pipeline.`,
      });
    }
  } catch (error) {
    console.error('Patch error:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}